### ISSUE TITLE
Calculating uncommon combinations of perks causes the system to become unresponsive

### ISSUE THREAD

**Issue by DennisCorvers** [ppartous/Runescape-perk-solver#2]
Due to the application creating new threads for parallel calculation, the CPU usage easily reaches 100%, causing the system to become fairly unresponsive.

Proposal of limiting the newly spawned threads for calculation to be threadcount -1 or -2 of what the system has.

**Comment by ppartous** [comment]
This is now an optional toggle in 1.7.0
